version: "3.9"
services:
  frontend:
    # docker run -v "$(pwd)":"$(pwd)" -w "$(pwd)" -p 80:3000 node:alpine ./frontend/run_dev_mode.sh
    image: "node:alpine"
    volumes:
      - type: bind
        source: "/Users/thabok/Git/mycartime"
        target: "/Users/thabok/Git/mycartime"
    working_dir: "/Users/thabok/Git/mycartime"
    command: "./frontend/run_dev_mode.sh"
    ports: 
      - "3000:3000"