name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build frontend
      run: |
        cd frontend
        npm ci
        npm run build
        mkdir -p deploy/frontend
        cp -r frontend/build deploy/frontend

    - name: Build backend
      run: |
        cd backend
        mvn clean package
        mkdir -p deploy/backend
        cp backend/target/my-car-time-1.0-SNAPSHOT-jar-with-dependencies.jar deploy/backend/

    - name: Create archive
      run: |
        cd deploy
        zip -r archive.zip .

    - name: Publish release
      uses: actions/upload-release-asset@v1
      with:
        tag_name: ${{github.ref}}
        release_id: ${{github.run_id}}
        asset_path: deploy/archive.zip
        asset_name: archive.zip
        asset_content_type: application/zip
