name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build
        mkdir -p ../deploy/frontend
        cp -r build ../deploy/frontend
        pwd

    - name: Build backend
      run: |
        pwd
        cd backend
        mvn clean package
        cp target/my-car-time-1.0-SNAPSHOT-jar-with-dependencies.jar ../deploy
        pwd

    - name: Create archive
      run: |
        pwd
        cd deploy
        zip -r mycartime_v${{github.run_id}}.zip .
        cd ..
        pwd

    - name: Publish release
      uses: actions/upload-release-asset@v1
      with:
        tag_name: ${{github.ref}}
        release_id: ${{github.run_id}}
        asset_path: deploy/mycartime_v${{github.run_id}}.zip
        asset_name: mycartime_v${{github.run_id}}.zip
        asset_content_type: application/zip
